name: Docker Preview Build

on:
  push:
    branches:
      - preview
jobs:
  docker-aio:
    name: Docker Preview Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Docker Setup Buildx
        uses: docker/setup-buildx-action@v1.2.0
      - name: Docker login
        run: echo ${{ secrets.GHCR_TOKEN }} | docker login -u ${{ github.repository_owner }} --password-stdin ghcr.io
      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          platforms: linux/amd64,linux/arm64,linux/arm/v7
          push: true
          tags: ghcr.io/${{ github.repository }}:preview,ghcr.io/${{ github.repository }}:preview-${GITHUB_SHA::8}